In [1]:
import numpy as np
from tools.sle_solvers import successive_over_relaxation, thomas

In [2]:
matrix = np.array([[2, 1, 0], [1, 3, 0], [0, 1, 2]])
b_ = np.array([4, 7, 5])

res = successive_over_relaxation(
    mat=matrix,
    b=b_,
    x_0=np.zeros_like(b_, dtype=float),
    eps=1e-10,
    omega=1.13,
)

print(res)

Solution found on iteration 13
[1.  2.  1.5]


In [3]:
matrix = np.array([[4, 4, 4, 2], [4, 8, 6, 4], [4, 6, 9, 7], [2, 4, 7, 7]])
b_ = np.array([24, 48, 60, 52])

res = successive_over_relaxation(
    mat=matrix, b=b_, x_0=np.ones_like(b_, dtype=float), omega=1
)
print(res)

Maximum iterations reached
[-4.25  3.75  4.5   2.  ]


In [4]:
# create the matrix

n = 1000
A = np.diag([3] * n, k=0) + np.diag([-1] * (n - 1), k=-1) + np.diag([1] * (n - 1), k=1)
f = np.array([1 / i for i in range(1, n + 1)])

print(f"size of A is {A.shape}")
print(f"size of f is {f.shape[0]}")

print(f"\nA is:\n{A}")
print(f"\nf is: {f}")

size of A is (1000, 1000)
size of f is 1000

A is:
[[ 3  1  0 ...  0  0  0]
 [-1  3  1 ...  0  0  0]
 [ 0 -1  3 ...  0  0  0]
 ...
 [ 0  0  0 ...  3  1  0]
 [ 0  0  0 ... -1  3  1]
 [ 0  0  0 ...  0 -1  3]]

f is: [1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
 0.07692308 0.07142857 0.06666667 0.0625     0.05882353 0.05555556
 0.05263158 0.05       0.04761905 0.04545455 0.04347826 0.04166667
 0.04       0.03846154 0.03703704 0.03571429 0.03448276 0.03333333
 0.03225806 0.03125    0.03030303 0.02941176 0.02857143 0.02777778
 0.02702703 0.02631579 0.02564103 0.025      0.02439024 0.02380952
 0.02325581 0.02272727 0.02222222 0.02173913 0.0212766  0.02083333
 0.02040816 0.02       0.01960784 0.01923077 0.01886792 0.01851852
 0.01818182 0.01785714 0.01754386 0.01724138 0.01694915 0.01666667
 0.01639344 0.01612903 0.01587302 0.015625   0.01538462 0.01515152
 0.01492537 0.01470588 0.01449275 0.01428571 0.01

In [5]:
# solve and time the process

from timeit import default_timer as timer


st = timer()
xt = thomas(A, f)
et = timer()
ss = timer()
xs = np.linalg.solve(A, f)
es = timer()
sg = timer()
xg = successive_over_relaxation(A, f, np.zeros_like(f, dtype=float))
eg = timer()

print(f"Gauss-Seidel: {eg-sg:.5f}s")
print(f"Thomas: {et-st:.5f}s")
print(f"NumPy: {es-ss:.5f}s")

Solution found on iteration 32
Gauss-Seidel: 14.41863s
Thomas: 0.00240s
NumPy: 0.15272s


In [6]:
# error analysis (here we calculate maximum absolute error between SciPy and our implementation of Thomas's algorithm)

print(f"err (Thomas vs NumPy): {np.max(np.abs(xt-xs)):.16f}")
print(f"err (Thomas vs Gauss-Seidel): {np.max(np.abs(xt-xg)):.16f}")
print(f"err (NumPy vs Gauss-Seidel): {np.max(np.abs(xs-xg)):.16f}")

err (Thomas vs NumPy): 0.0000000000000000
err (Thomas vs Gauss-Seidel): 0.0000000000081785
err (NumPy vs Gauss-Seidel): 0.0000000000081785
