In [10]:
import numpy as np
from tools.sle_solvers import successive_over_relaxation, thomas

In [11]:
matrix = np.array([[2, 1, 0], [1, 3, 0], [0, 1, 2]])
b_ = np.array([4, 7, 5])

res = successive_over_relaxation(
    mat=matrix,
    b=b_,
    x_0=np.zeros_like(b_, dtype=float),
    eps=1e-10,
    omega=1.13,
)

print(res)

Iteration  1 | Stop Condition = 0.2553692390 | X = [2.26     1.7854   1.816249]
Iteration  2 | Stop Condition = 0.0139001553 | X = [0.957449   2.04392554 1.4340697 ]
Iteration  3 | Stop Condition = 0.0045596967 | X = [0.9807137  2.00155419 1.50769282]
Iteration  4 | Stop Condition = 0.0003370223 | X = [1.0016291  1.99918433 1.49946079]
Iteration  5 | Stop Condition = 0.0000633620 | X = [1.00024907 2.00001222 1.50006319]
Iteration  6 | Stop Condition = 0.0000071502 | X = [0.99996072 2.00001321 1.49998432]
Iteration  7 | Stop Condition = 0.0000008925 | X = [0.99999764 1.99999917 1.50000251]
Iteration  8 | Stop Condition = 0.0000001602 | X = [1.00000078 1.99999982 1.49999978]
Iteration  9 | Stop Condition = 0.0000000100 | X = [1.         2.00000002 1.50000002]
Iteration 10 | Stop Condition = 0.0000000027 | X = [0.99999999 2.         1.5       ]
Iteration 11 | Stop Condition = 0.0000000001 | X = [1.  2.  1.5]
Iteration 12 | Stop Condition = 0.0000000000 | X = [1.  2.  1.5]
Solution found o

In [12]:
matrix = np.array([[4, 4, 4, 2], [4, 8, 6, 4], [4, 6, 9, 7], [2, 4, 7, 7]])
b_ = np.array([24, 48, 60, 52])

res = successive_over_relaxation(
    mat=matrix, b=b_, x_0=np.ones_like(b_, dtype=float), omega=1
)
print(res)

Iteration  1 | Stop Condition = 0.2340795966 | X = [3.         3.25       2.38888889 2.32539683]
Iteration  2 | Stop Condition = 0.0617581503 | X = [-1.96428571  4.02777778  3.04585538  2.64235324]
Iteration  3 | Stop Condition = 0.0381409086 | X = [-3.71598639  4.25242504  3.42810252  2.63222214]
Iteration  4 | Stop Condition = 0.0475902926 | X = [-4.3127497   4.26918689  3.69003583  2.53121443]
Iteration  5 | Stop Condition = 0.0506297358 | X = [-4.49043715  4.21208449  3.88563785  2.4190102 ]
Iteration  6 | Stop Condition = 0.0502973116 | X = [-4.51673254  4.13463278  4.03622912  2.32019002]
Iteration  7 | Stop Condition = 0.0489340971 | X = [-4.49105192  4.05825911  4.15259143  2.24013248]
Iteration  8 | Stop Condition = 0.0474451287 | X = [-4.45098302  3.9909817   4.24190162  2.17781828]
Iteration  9 | Stop Condition = 0.0461286506 | X = [-4.41070159  3.93501545  4.30977619  2.13041543]
Iteration 10 | Stop Condition = 0.0450545400 | X = [-4.37520707  3.89006367  4.36083758  2.0948

In [13]:
# create the matrix

n = 1000
A = np.diag([3] * n, k=0) + np.diag([-1] *
                                    (n-1), k=-1) + np.diag([1] * (n-1), k=1)
f = np.array([1/i for i in range(1, n+1)])

print(f"size of A is {A.shape}")
print(f"size of f is {f.shape[0]}")

print(f"\nA is:\n{A}")
print(f"\nf is: {f}")

size of A is (1000, 1000)
size of f is 1000

A is:
[[ 3  1  0 ...  0  0  0]
 [-1  3  1 ...  0  0  0]
 [ 0 -1  3 ...  0  0  0]
 ...
 [ 0  0  0 ...  3  1  0]
 [ 0  0  0 ... -1  3  1]
 [ 0  0  0 ...  0 -1  3]]

f is: [1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
 0.07692308 0.07142857 0.06666667 0.0625     0.05882353 0.05555556
 0.05263158 0.05       0.04761905 0.04545455 0.04347826 0.04166667
 0.04       0.03846154 0.03703704 0.03571429 0.03448276 0.03333333
 0.03225806 0.03125    0.03030303 0.02941176 0.02857143 0.02777778
 0.02702703 0.02631579 0.02564103 0.025      0.02439024 0.02380952
 0.02325581 0.02272727 0.02222222 0.02173913 0.0212766  0.02083333
 0.02040816 0.02       0.01960784 0.01923077 0.01886792 0.01851852
 0.01818182 0.01785714 0.01754386 0.01724138 0.01694915 0.01666667
 0.01639344 0.01612903 0.01587302 0.015625   0.01538462 0.01515152
 0.01492537 0.01470588 0.01449275 0.01428571 0.01

In [16]:
# solve and time the process

from timeit import default_timer as timer


st = timer()
xt = thomas(A, f)
et = timer()
ss = timer()
xs = np.linalg.solve(A, f)
es = timer()
sg = timer()
xg = successive_over_relaxation(A, f, np.zeros_like(f, dtype=float))
eg = timer()

print(f"Gauss-Seidel: {eg-sg:.5f}s")
print(f"Thomas: {et-st:.5f}s")
print(f"NumPy: {es-ss:.5f}s")

Iteration  1 | Stop Condition = 0.3542987768 | X = [0.33333333 0.27777778 0.2037037  0.15123457 0.11707819 0.09458162
 0.07914625 0.06804875 0.05971995 0.05323998 0.04804969 0.04379434
 0.04023914 0.03722257 0.03462975 0.03237658 0.03040004 0.02865186
 0.02709448 0.02569816 0.02443907 0.02329787 0.02225871 0.02130846
 0.02043615 0.01963256 0.01888987 0.01820138 0.01756138 0.0169649
 0.01640766 0.01588589 0.01539631 0.01493602 0.01450248 0.01409342
 0.01370682 0.01334087 0.01299396 0.01266465 0.01235163 0.01205372
 0.01176984 0.01149904 0.01124042 0.01099318 0.01075659 0.01052998
 0.01031271 0.01010424 0.00990403 0.0097116  0.00952651 0.00934834
 0.00917672 0.00901129 0.00885172 0.0086977  0.00854895 0.00840521
 0.00826622 0.00813175 0.00800159 0.00787553 0.00775338 0.00763497
 0.00752011 0.00740867 0.00730047 0.0071954  0.0070933  0.00699406
 0.00689756 0.00680369 0.00671234 0.00662341 0.00653681 0.00645244
 0.00637022 0.00629007 0.00621192 0.00613568 0.00606129 0.00598868
 0.0059178  

In [17]:
# error analysis (here we calculate maximum absolute error between SciPy and our implementation of Thomas's algorithm)

print(f"err (Thomas vs NumPy): {np.max(np.abs(xt-xs)):.16f}")
print(f"err (Thomas vs Gauss-Seidel): {np.max(np.abs(xt-xg)):.16f}")
print(f"err (NumPy vs Gauss-Seidel): {np.max(np.abs(xs-xg)):.16f}")

err (Thomas vs NumPy): 0.0000000000000000
err (Thomas vs Gauss-Seidel): 0.0000000000081785
err (NumPy vs Gauss-Seidel): 0.0000000000081785
