In [23]:
import numpy as np
import scipy
from tools.sle_solvers import very_rapid_thomas_algorithm as solver

In [24]:
# create the matrix

n = 5000
A = np.diag([100]*5000, k=0)+np.diag([-2]*4999, k=-1)+np.diag([-2]*4999, k=1)
f = np.array([4, -2]*2500)

print(f'size of A is {A.shape}')
print(f'size of f is {f.shape[0]}')

print(f'\nA is:\n{A}')
print(f'\nf is: {f}')

size of A is (5000, 5000)
size of f is 5000

A is:
[[100  -2   0 ...   0   0   0]
 [ -2 100  -2 ...   0   0   0]
 [  0  -2 100 ...   0   0   0]
 ...
 [  0   0   0 ... 100  -2   0]
 [  0   0   0 ...  -2 100  -2]
 [  0   0   0 ...   0  -2 100]]

f is: [ 4 -2  4 ... -2  4 -2]


In [25]:
# solve and time the process

from timeit import default_timer as timer


st = timer()
xt = solver(A, f)
et = timer()
ss = timer()
xs = scipy.linalg.solve(A, f)
es = timer()

print(f'As we can see Thomas\'s algorithm is {(es-ss)/(et-st):.2f} faster.')

As we can see Thomas's algorithm is 111.03 faster.


In [26]:
# error analysis (here we calculate maximum absolute error between SciPy and our implementation of Thomson's algorithm)

np.max(np.abs(xt-xs))

0.0